services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobile_money
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5008:5008"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mobile_money
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
